# 球体原型, 数组中每一行代表一种原型. 目前要求必须有4种原型
# 如果想要更少可以将, 相应的数量设置成0
# 除了颜色和数量外的系数配置不当可能造成模拟结果失真
sphere-protos = [
    # spring, damping, shear, mass, radius, color,              num,
    [ 0.3,    0.02,    0.1,   0.04, 0.0625, [0.99, 0.40, 0.40], 10],
    [ 1.0,    0.02,    0.1,   0.02, 0.0417, [0.60, 0.99, 0.60], 500],
    [ 0.8,    0.02,    0.1,   0.02, 0.0313, [0.68, 0.93, 0.93], 100],
    [ 0.8,    0.02,    0.1,   0.01, 0.0208, [0.99, 0.89, 0.71], 1000],
]

# 渲染窗口的配置
[renderer]
width = 800         # 窗口大小, 启动后不能再更改
height = 800
fps = 30            # 帧率
sphere_frag = 32    # 控制每个球体渲染所用的三角面片, 越大渲染效果越好但也越消耗资源
move_diff = 0.005   # 相机移动的相对幅度
rot_diff = 1.0      # 相机旋转的相对幅度

# 全局的物理环境配置
[physics]
gravity = [0.0, -0.5, 0.0]  # 模拟重力方向和大小, 默认y轴负方向是重力方向
bnd_friction = 0.1          # 边界的摩擦系数
